return {
  "SirZenith/oil-vcs-status",
  dependencies = { "stevearc/oil.nvim" },
  opts = function()
    local status_const = require("oil-vcs-status.constant.status")
    local StatusType = status_const.StatusType
    return {
      status_symbol = {
        [StatusType.Added] = "",
        [StatusType.Copied] = "󰆏",
        [StatusType.Deleted] = "",
        [StatusType.Ignored] = "",
        [StatusType.Modified] = "",
        [StatusType.Renamed] = "",
        [StatusType.TypeChanged] = "󰉺",
        [StatusType.Unmodified] = " ",
        [StatusType.Unmerged] = "",
        [StatusType.Untracked] = "",
        [StatusType.External] = "",

        [StatusType.UpstreamAdded] = "󰈞",
        [StatusType.UpstreamCopied] = "󰈢",
        [StatusType.UpstreamDeleted] = "",
        [StatusType.UpstreamIgnored] = " ",
        [StatusType.UpstreamModified] = "󰏫",
        [StatusType.UpstreamRenamed] = "",
        [StatusType.UpstreamTypeChanged] = "󱧶",
        [StatusType.UpstreamUnmodified] = " ",
        [StatusType.UpstreamUnmerged] = "",
        [StatusType.UpstreamUntracked] = " ",
        [StatusType.UpstreamExternal] = "",
      },
      status_hl_group = {
        [StatusType.Added] = false,
        [StatusType.Copied] = false,
        [StatusType.Deleted] = false,
        [StatusType.Ignored] = false,
        [StatusType.Modified] = false,
        [StatusType.Renamed] = false,
        [StatusType.TypeChanged] = false,
        [StatusType.Unmodified] = false,
        [StatusType.Unmerged] = false,
        [StatusType.Untracked] = false,
        [StatusType.External] = false,
        [StatusType.UpstreamAdded] = false,
        [StatusType.UpstreamCopied] = false,
        [StatusType.UpstreamDeleted] = false,
        [StatusType.UpstreamIgnored] = false,
        [StatusType.UpstreamModified] = false,
        [StatusType.UpstreamRenamed] = false,
        [StatusType.UpstreamTypeChanged] = false,
        [StatusType.UpstreamUnmodified] = false,
        [StatusType.UpstreamUnmerged] = false,
        [StatusType.UpstreamUntracked] = false,
        [StatusType.UpstreamExternal] = false,
      },
    }
  end,
}
